model_config:
  MobileNetV2:
    output_layer: classifier.1
    prevent_binarization:
      - features.0.0
      - classifier.1

  vgg16:
    output_layer: classifier.6
    prevent_binarization:
      - features.0
      - classifier.6

  vgg19:
    output_layer: classifier.6
    prevent_binarization:
      - features.0
      - classifier.6

  MLPMixer:
    output_layer: 16
    prevent_binarization:
      - 1
      - 16

  aevgg16:
    output_layer: decoder.conv5.2 DecoderLayer.layer.2
    prevent_binarization:
      - encoder.conv1.0 EncoderLayer.layer.0
      - decoder.conv5.2 DecoderLayer.layer.2

  aevgg19:
    output_layer: decoder.conv5.2 DecoderLayer.layer.2
    prevent_binarization:
      - encoder.conv1.0 EncoderLayer.layer.0
      - decoder.conv5.2 DecoderLayer.layer.2